### ISSUE TITLE
Add new plots/statistics to all tabs

### ISSUE THREAD

**Issue by fvitalini** [miraisolutions/Covid19#5]
e.g. death rate

**Comment by GuidoMaggio** [comment]
Feedback from call 02.04

lineplot on left, cut at 1000 cases, check, in this ticket we wrote 100. We must visualise what makes more sense. If for global plot 1000 would be fine, for a country comparison we may like to cut 100.

The 2 barplots on the right:
1)
Growth factor in X number of days (i.e. confirmed cases today / confirmed cases X days ago)
- options (ticks), 2 weeks, 1 week, 3 days
- number of cases today / number of cases X days ago
N.B the same ratio above could be done for Active Cases, then it would become negative when going down

A growth ratio would show also better in a comparison graph than the number of days required for doubling

2)
Death rate / letality rates (2 ticks, 1 box)
- deaths/ population (per 100'000 people of 1 million)
- deaths / number of confirmed cases
lineplot of such factor (in middle position):
I do not see lineplots for these rates above, specially death rate because it will be a flat line (Italy was always 12%)
Growth factor would be possibly similarly uninteresting (we can check if informative).
I see these plots more for country and country comparisons plot
Country (this would be new plot, not for now):
- barplot of growth rate per week (like time series)
- barplot of death rate per week (not cumulative!, then we see a change, to check how to do it)

Country comparison
- both lineplots on left and barplots on right are perfect for country comparison
- same as in global page, we can obtain this easily, filters on 10K to be removed (edited)
