### ISSUE TITLE
Reverse colours in covid smarp plot

### ISSUE THREAD

**Issue by GuidoMaggio** [miraisolutions/Covid19#74]
In the stacked line plot smarp style we have from bottom to top
- deaths 
- recovered 
- active 

Total makes confirmed.
In the country page the order is different, this is actually a bug.

Invert order to show better the curve of active, the downward trend.  

From bottom to top:
- active
- deaths
- recovered

**Comment by riccardoporreca** [comment]
@GuidoMaggio, @StefGehring, the way the order is currently  implemented was defined as part of #33, where we originally discussed to to have the active cases at the bottom in order to eventually show the nice "bell-shaped" trend:

> have the active as first plot (can be covered in this issue)

but this was not a sensible choice, especially in view of the log plots, which are very useful but suffer from the order:
> This was in fact not a sensible choice, since with the log plots it makes more sense to have closer to the x axis the data with smaller amounts. This logic has been now implemented

_Originally posted by @riccardoporreca in https://github.com/miraisolutions/Covid19/issues/33#issuecomment-601846473_

Just want to make sure the proposed change here took this into consideration. Given that we have a clear  coloring scheme, I am not sure if forcing the same order pays off if we loose readability on the log scale.

**Comment by GuidoMaggio** [comment]
hi Riccardo

thanks for your comment and for pointing out a possible problem with the log version of the plot.

I fear however the choice made in #33 was not so lucky.
The correct order, also shown in 99% of such plots, is what I have defined here in #74.
In this way it will be consistent, readable and less confusing.

The log version is honestly already uninformative in this plot.
If the change in colors order would mess the log version of this plot I suggest to remove it as part of this ticket. Actually we should evaluate to remove it even if it looks decent.

**Comment by riccardoporreca** [comment]
@GuidoMaggio, I personally look at log plots more than linear plots, this is why in #33 the order we already wanted back then (and which is being re-imposed now) was replaced with such a dynamic order.
Never mind, whatever you believe is the most reasonable thing overall as of now.

**Comment by GuidoMaggio** [comment]
I look at the log plots too, but of the other graphs, in this one the log version does not really add much.
If it does not look nice we can remove it.

I know we revert a decision, but honestly with data changing also things can change.
Furthermore now we have chance to observe many more other plots from other sites than we had when we started with #33
